### ISSUE TITLE
大佬还更新吗

### ISSUE THREAD

**Issue by qud123** [XuanRanDev/Auto-ZhiXiaoJiaYuan-SCF#11]
大佬还更新吗

**Comment by 156313vvj** [comment]
大佬应该不想更了

**Comment by HuanHren** [comment]
希望更新，我见有人还在卖说什么平台已经更新了，大力打击这种⭕️🐶

**Comment by XuanRanDev** [comment]
等着 会更新的 这两天有事

**Comment by 156313vvj** [comment]
呜呜呜 大佬我要给你生猴子

**Comment by qud123** [comment]
> 等着 会更新的 这两天有事

好的大佬。今天刚开始我还以为我电脑有问题了，我给python重新安装了一遍了然后登录发现是算法更新了

**Comment by HuanHren** [comment]
> 等着 会更新的 这两天有事

最看不惯，⭕️钱的了，用的开源的还⭕️钱，MD受不了

**Comment by qud123** [comment]
昨天晚上我抓包看了一下，他更新sign算法认证了，我已经改好了大佬！

**Comment by sterobun** [comment]
> 昨天晚上我抓包看了一下，他更新sign算法认证了，我已经改好了大佬！

大佬咋改的？

**Comment by sterobun** [comment]
> 等着 会更新的 这两天有事

大佬爱你

**Comment by XuanRanDev** [comment]
临时api接口已开发完毕，只需加一个新文件即可完成打卡任务，之前赞助>30的联系我，剩余的等正式的接口吧。。。（还是会免费的，只是时间问题）
