### ISSUE TITLE
职校家园更新的，打开不了了

### ISSUE THREAD

**Issue by iwbiu** [XuanRanDev/Auto-ZhiXiaoJiaYuan-SCF#12]
职屏家园登录失败！当前网络不佳，请关闭APP切换网络后重新再试

**Comment by sterobun** [comment]
大佬，现在软件还有自动检查是否存在作弊已经有很多人被检查出来疑似作弊被驳回了

**Comment by XuanRanDev** [comment]
> 大佬，现在软件还有自动检查是否存在作弊已经有很多人被检查出来疑似作弊被驳回了

用的是公众号新发的那个修补文件吗，如果是的话很可能和ip有关系
