### ISSUE TITLE
错误原因：Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by GSZ-FENGLIN** [XuanRanDev/Auto-ZhiXiaoJiaYuan-SCF#5]
报错什么原因？
找到配置文件，将从配置文件加载信息！
已加载用户 张三 即将开始打卡
职校家园打卡失败，错误原因：Expecting value: line 1 column 1 (char 0)
推送消息提醒失败！

**Comment by 12321zxcvbnm** [comment]
[
  {
    "enable": true,
    "alias": "k晒",
    "phone": "17739244561",
    "password": "1ZXCVBNM",
    "deviceType": "Xiaomi|Mi 13|13",
    "deviceId": "038b8d237d7c4c9fa1e64dd6cabac66fce4a",
    "randomLocation": true,
    "address": "河南省鹤壁市山城区枫岭公园内广场西北角山城路61号",
    "longitude": "114.173752",
    "latitude": "35.891541",
    "pushKey":
"8eca12803edc471fa585c9b91b47fbb8"
  }
]

**Comment by LuYanBiao** [comment]
蹲~

**Comment by 156313vvj** [comment]
没连接到服务器
