### ISSUE TITLE
怎么抓到包的可以分享一下吗

### ISSUE THREAD

**Issue by q1692306918** [XuanRanDev/Auto-ZhiXiaoJiaYuan-SCF#6]
试了一下用fiddler抓手机(不是模拟器)，但是看不到数据包，可以指点一下吗

**Comment by Live92** [comment]
> 试了一下用fiddler抓手机(不是模拟器)，但是看不到数据包，可以指点一下吗

fiddler+手机 或者 fiddler + 模拟器 这两种方案应该实现抓包，需要安装一下fiddler的证书。准备周末回家试试。希望能加个学习小组。
